homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret my_latitude
  longitude: !secret my_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 165
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

#http:
  # Secrets are defined in the file secrets.yaml
  #api_password: !secret http_password
  # ssl_certificate: !secret sec_ssl_cert
  # ssl_key: !secret sec_ssl_key
  # base_url: !secret sec_base_url

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
   - google_cast

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# nest:
#   client_id: !secret nest_clientid
#   client_secret: !secret nest_clientsecret

octoprint:
  host: 192.168.254.105
  port: 5000
  api_key: !secret octoprint_api_key
  name: Prusa i3 Hephestos
  number_of_tools: 1
  sensors:
    monitored_conditions:
     - 'Current State'
     - 'Job Percentage'
     - 'Temperatures'

# Weather prediction
sensor:
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - cloud_cover
      - precip_probability
      - wind_speed
      - humidity
      - pressure
      - temperature
  - platform: template
    sensors:
      bedroom_lamp_amps:
        friendly_name: 'Current'
        value_template: '{{ states.switch.bedroom_lamp.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: 'A'
      bedroom_lamp_watts:
        friendly_name: 'Power'
        value_template: '{{ states.switch.bedroom_lamp.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
      bedroom_lamp_total_kw:
        friendly_name: 'Total Power'
        value_template: '{{ states.switch.bedroom_lamp.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kW'
      bedroom_lamp_volts:
        friendly_name: 'Voltage'
        value_template: '{{ states.switch.bedroom_lamp.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: 'V'
      living_room_lamp_watts:
        friendly_name: 'Power'
        value_template: '{{ states.switch.living_room_lamp.attributes["current_power_w"] | replace(" W", "") | float }}'
        unit_of_measurement: 'W'
      living_room_lamp_total_kw:
        friendly_name: 'Total Power'
        value_template: '{{ states.switch.living_room_lamp.attributes["total_energy_kwh"] | replace(" kW", "") | float }}'
        unit_of_measurement: 'kW'
      living_room_lamp_volts:
        friendly_name: 'Voltage'
        value_template: '{{ states.switch.living_room_lamp.attributes["voltage"] | replace(" V", "") | float }}'
        unit_of_measurement: 'V'
      living_room_lamp_amps:
        friendly_name: 'Current'
        value_template: '{{ states.switch.living_room_lamp.attributes["current_a"] | replace(" A", "") | float }}'
        unit_of_measurement: 'A'
      printer_amps:
        friendly_name_template: '{{ states.switch.garage_printer.name}} Current'
        value_template: '{{ states.switch.garage_printer.attributes["current_a"] | float }}'
        unit_of_measurement: 'A'
      printer_watts:
        friendly_name_template: "{{ states.switch.garage_printer.name}} Power"
        value_template: '{{ states.switch.garage_printer.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
      printer_kw:
        friendly_name_template: "{{ states.switch.garage_printer.name}} Daily Power"
        value_template: '{{ states.switch.garage_printer.attributes["total_energy_kwh"] | float }}'
        unit_of_measurement: 'kW'
      printer_volts:
        friendly_name_template: "{{ states.switch.garage_printer.name}} Voltage"
        value_template: '{{ states.switch.garage_printer.attributes["voltage"] | float}}'
        unit_of_measurement: 'V'
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
  # - platform: mqtt
  #   state_topic: "octoprint/#"
  - platform: octoprint

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# mqtt:
#   broker: 192.168.254.105
#   port: 1883
#   birth_message:
#     topic: 'hass/status'
#     payload: 'online'
#   will_message:
#     topic: 'hass/status'
#     payload: 'offline'

tplink:

ecobee:
  api_key: !secret ecobee_api_key

# influxdb:
#   host: 192.168.254.107
#   port: 8086
#   database: homeassistant
#   default_measurement: state
# #  exclude:
# #    entities:
# #     - sensor.dark_sky_temperature
#   include:
#     domains:
#      - sensor
#      - binary_sensor
#      - climate
  #  entities:
  #   - sensor.dark_sky_temperature
  #   - sensor.guest_bedroom_temperature
  #   - sensor.home_temperature
  #   - sensor.living_room_temperature
  #   - sensor.master_bedroom_temperature

# Cloud
cloud:

system_health:

camera:
  - platform: local_file
    file_path: /home/homeassistant/.homeassistant/images/mail_and_packages/mail_today.gif
    name: mail_usps

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
